### ISSUE TITLE
bottom-right should come before bottom-left

### ISSUE THREAD

**Issue by thewildmage** [rp-magrathea/stylelint-alphabetical-clockwise-order#3]
Order should be clockwise, to match the way it'd be defined if you used the shorthand `border-radius` with four values:
```css
.test {
    border-top-left-radius: 100%;
    border-top-right-radius: 100%;
    border-bottom-right-radius: 100%;
    border-bottom-left-radius: 100%;
}
```
Currently, there's an error being thrown saying that the last two lines of this example should be switched.
